Add bottom bar to the home menu
vostpt/mobile-app pull request #56
Opened 2019-08-31 22:04 UTC by Vanethos

Add bottom bar to the home menu with:
- Callbacks for each button
- Each button click is wired to the BLoC
- A pop up menu

Added colors file
Added dimmensions file
Added text styles file
Added primary and accent color to app

#closes 24

2019-08-31 23:10 UTC, miguelpruivo approved these changes

2019-08-31 23:10 UTC, miguelpruivo commented on lib/presentation/assets/colors.dart
> +const colorAccent = Color(0xFFFBC02D);
**Sugestão:** Não será boa ideia extrairmos isto para uma classe que possa fazer a gestão do tema? Mesmo que sejam cores estáticas.

2019-08-31 23:10 UTC, miguelpruivo approved these changes

2019-08-31 23:11 UTC, miguelpruivo approved these changes

2019-08-31 23:28 UTC, Vanethos commented on lib/presentation/assets/colors.dart
> +const colorAccent = Color(0xFFFBC02D);
I think that could be a nice solution, indeed, should we open a new issue for that?

2019-08-31 23:49 UTC, miguelpruivo commented on lib/presentation/ui/home/home_page.dart
> +                              // since the onClick is handled by another widget, this
Aqui sugiro colocar o `onPressed: null` para evitar warnings (apesar de ser redundante).

2019-08-31 23:49 UTC, miguelpruivo commented on lib/presentation/utils/misc.dart
> +  textPainter.text = TextSpan(text: text, style: style);
Mudar aqui o `text` para `text.toUpperCase()`.

2019-08-31 23:49 UTC, miguelpruivo commented on lib/presentation/ui/home/home_page.dart
> +                        width: _findBiggestTextWidth() * 1.5,
Remover o `*1.5`.

2019-08-31 23:50 UTC, miguelpruivo requested changes
Ver comentários.

2019-09-01 00:05 UTC, miguelpruivo commented on lib/presentation/assets/colors.dart
> +const colorAccent = Color(0xFFFBC02D);
Yes, that could fit in a low priority issue.

2019-09-01 10:34 UTC, Vanethos commented
Fixed comments

2019-09-01 10:59 UTC, miguelpruivo approved these changes

2019-09-01 10:59 UTC, merged