Update podfile.lock
vostpt/mobile-app pull request #60
Opened 2019-09-02 17:32 UTC by Vanethos

Closes #59

2019-09-02 17:48 UTC, OldMetalmind approved these changes

2019-09-02 17:55 UTC, OldMetalmind commented
Let add Podfile.lock to the `.gitignore`

2019-09-02 17:56 UTC, OldMetalmind requested changes
@Vanethos Let add Podfile.lock to the .gitignore

To avoid people with different cocoa pods version to keep changing this.

2019-09-03 00:07 UTC, miguelpruivo approved these changes

2019-09-04 15:36 UTC, OldMetalmind approved these changes

2019-09-05 21:52 UTC, merged