Report Problem Screen added
vostpt/mobile-app pull request #63
Opened 2019-10-01 05:31 UTC by 404shades

2019-10-01 11:01 UTC, Vanethos requested changes
Please view the requested changes

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/app.dart
> +        routeProblem:(context)=>ProblemReport()
Please format your code. Also, use the style in the other page, so in this case it should be `ProblemReportPage`

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +class ProblemReport extends StatefulWidget {
The class should be named `ProblemReportPage`
The file name is in lowercase separated by `_`

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +  final email = "email@email.com";
the e-mail address should be in the `constants.dart` file

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +      throw Exception("Could not launch $url");
If there is an exception, shouldn't we warn the user with a snackbar or a toast?

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +        title: Text("Reportar Problema",style: TextStyle(color: Colors.white),),
For strings please use the VostLocalizations file. There are instructions for adding the strings there

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +        padding: const EdgeInsets.all(19),
Why 19?

Also, dimensions should be added as constants on `dimensions.dart`

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +            SizedBox(height: 40,),
size should be added to `dimensions.dart`

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +  @override
Folder name should lowercase, please follow the convention in the other files and folders

2019-10-01 11:01 UTC, Vanethos commented on ios/Flutter/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
Please add this file to the git ignore as it is stated in this line:
` # This is a generated file; do not edit or check into version control.`
And remove it from your PR

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/navigation/navigation.dart
> +const routeProblem = "/problemReport";
since this is a subpage from home, change it to `/home/problemReport`

2019-10-01 11:01 UTC, Vanethos commented on lib/presentation/ui/ProblemReport/ReportProblem.dart
> +class ProblemReport extends StatefulWidget {
Why do we need a StatefulWidget in this case? Can't it be a `StatelessWidget`?

2019-10-01 11:01 UTC, Vanethos commented on pubspec.yaml
> +
remove the unnecessary lines

2019-10-01 11:03 UTC, Vanethos commented
Also please reference the issue that you are fixing as such: #16

2019-10-01 11:36 UTC, 404shades reviewed
I have changed as per your comments

2019-10-03 12:44 UTC, Vanethos commented on lib/presentation/assets/colors.dart
> +const colorPrimary = Color(0xFFFF5722);
Why are you changing the colors in this commit?

2019-10-03 12:45 UTC, Vanethos commented
@404shades before approving your commit, please check that it has merge conflicts, after they are resolved I'll approve the PR

2019-10-12 15:18 UTC, Vanethos commented
@404shades I'll approve the PR now.

Thanks for your work!

2019-10-12 15:19 UTC, Vanethos approved these changes

2019-10-12 15:19 UTC, merged