Feature: On Site Help Widget Implementation (#21)
vostpt/mobile-app pull request #86
Opened 2019-10-22 15:57 UTC by TomerPacific

Adding the implementation for the on site help widget. This widget is a Stateless widget which receivers four parameters :

- A DateTime Object
- Three Integers

Per the description, the callback is redacted. For now, since the preferred assets are not available, the usage of the vost_logo_white asset was used.

This is why the background is black and the text color is white.

Resolves #21

2019-10-22 18:13 UTC, Vanethos requested changes
Apart from the comments please see the following:

<img width="455" alt="imagem" src="https://user-images.githubusercontent.com/10728633/67316176-04801080-f519-11e9-8a31-260db59377a2.png">

- The background is in black
- There is no margin between the text/image and the border of the widget, please see the original issue to see that there was a padding

2019-10-22 18:13 UTC, Vanethos commented on lib/presentation/utils/constants.dart
> +library constants;
Why is this a library?

2019-10-22 18:13 UTC, Vanethos commented on lib/presentation/ui/on_site_help_widget.dart
> +                                    this._humanMeans.toString(),
what happens is this value is null?

2019-10-22 18:13 UTC, Vanethos commented on lib/presentation/ui/on_site_help_widget.dart
> +                                    this._humanMeans.toString(),
And the same for the others

2019-10-25 05:14 UTC, TomerPacific commented on lib/presentation/utils/constants.dart
> +library constants;
@Vanethos , as I mentioned in the PR, I kept the background black so you could see the images (as they are white). If the background was white, you would not see the images and then you would have probably said, "where are the images?".
I wanted to create a constants class so I can reuse the constants for the getFormattedDate method and I read that creating a class and naming it a library is one way to do it. If you would prefer to do it another way, let me know.

2019-10-25 05:57 UTC, TomerPacific commented on lib/presentation/ui/on_site_help_widget.dart
> +                                    this._humanMeans.toString(),
@Vanethos , what would you have printed when the value is null? "--"?

2019-10-25 08:39 UTC, Vanethos commented on lib/presentation/ui/on_site_help_widget.dart
> +                                    this._humanMeans.toString(),
Yes, maybe it's best to go with the convention we used in the other ones

2019-10-25 08:40 UTC, Vanethos commented on lib/presentation/utils/constants.dart
> +library constants;
You can remove it and use this throughout the project with no problem :D 

I'm not saying this is a bad idea! But I'll have to look more into the issue since it will affect more area (assets constants, colors constants, etc..)

2019-10-25 08:41 UTC, Vanethos commented on lib/presentation/utils/constants.dart
> +library constants;
As for the background, you can then put it white, we'll put the correct images on our side!

2019-10-25 08:42 UTC, Vanethos commented
@TomerPacific 
Just one thing after you see the comments, please check that there are now conflicts with the `misc.dart` file. If you can resolve them that'd be great!

2019-10-25 12:24 UTC, TomerPacific commented
@Vanethos , I'm seeing the build fail on this:
```Getter not found: 'MAPBOX_URL_TEMPLATE'``` inside home.dart. This is a file I haven't edited, any idea why?

2019-10-25 12:47 UTC, Vanethos commented
@TomerPacific Yes, give me 10 minutes, sorry about that!

2019-10-25 12:49 UTC, Vanethos commented
@TomerPacific 

Either follow these instructions:

```
/*
 * Map Widget
 *
 * In order to use the map widget, a `keys.dart` file must be created at the root
 * of the project with the following constants:
 *
 * `MAPBOX_ACCESS_TOKEN` - the token for mapbox
 * `MAPBOX_URL_TEMPLATE` the template for mapbox, this can have the default value of
 *      `https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}`
 *
 * In order to have a new key, go to https://www.mapbox.com/ and create a free account
 * and a project for this open-source project
 */
```

Or you can (for testing purposes) put them both as `""`

2019-10-25 14:10 UTC, TomerPacific commented
@Vanethos ,
I am going to create the file and put both values as empty strings.

2019-10-25 14:12 UTC, Vanethos commented
If I did not break up the git ignore file, then it shouldn't be going to the version control when you try to commit it!

2019-10-25 14:59 UTC, TomerPacific commented
@Vanethos , build is still failing on related issues, even though it runs locally. Any suggestions?

2019-10-25 16:02 UTC, Vanethos commented
@TomerPacific

As I said the keys.dart file should be just added for you locally so if you can remove it from your PR that would be great!

As for Travis we will have to use environment variables for that so that it can build the app, we didn't have time yet for it!

2019-10-25 17:44 UTC, TomerPacific commented
@Vanethos , I removed the keys.dart file

2019-10-27 11:20 UTC, Vanethos approved these changes
Thanks for the awesome PR as always @TomerPacific !!

2019-10-27 11:21 UTC, merged