Location permission on Map
vostpt/mobile-app pull request #93
Opened 2019-10-27 12:44 UTC by Vanethos

Add location permissions to map screen

2019-10-28 18:09 UTC, miguelpruivo requested changes

2019-10-28 18:09 UTC, miguelpruivo commented on lib/presentation/ui/home/home_page.dart
> +              "This app needs the GPS location so that it can show where you are in this map, do you want to allow it?",
Shouldn't this be on internalization support?

2019-10-28 18:09 UTC, miguelpruivo commented on lib/presentation/ui/home/home_page.dart
> +              "Allow Location".toUpperCase(),
The same.

2019-10-28 18:09 UTC, miguelpruivo commented on lib/presentation/ui/home/home_page.dart
> +        Container(child: Text("Permissions", style: styleIntroTitle(),)),
Shouldn't this be on internalization support?

2019-10-28 18:32 UTC, Vanethos commented
Regarding the comment: you are right, but since we don't have yet the copy, I thought of opening an issue in the future about it

2019-11-02 14:07 UTC, miguelpruivo approved these changes
Internalization support will be added on the future.

2019-11-02 14:07 UTC, merged